module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      // Lets Metro bundle the .sql files generated by drizzle-kit.
      ['inline-import', { extensions: ['.sql'] }],
    ],
  };
};
